added alt attributes to img elements
GoogleChromeLabs/quicklink pull request #362
Opened 2023-04-20 11:37 UTC by Udassi-Pawan

I added appropriate alt attributes to images with https links while for local images, I added the name of respective image to the alt prop.
I am relatively newer to open source contributions, thus if there is any change to be made, do let me know.

2023-04-20 13:27 UTC, XhmikosR requested changes

2023-04-20 13:27 UTC, XhmikosR commented on README.md
> +  <img src="https://raw.githubusercontent.com/GoogleChromeLabs/quicklink/HEAD/assets/images/logos/banner-white-bg.png" alt="quicklink logo" width="640">
This is presentational, it can be left empty as it was

2023-04-20 13:27 UTC, XhmikosR commented on site/src/_includes/components/download.njk
> +    <img src="/assets/images/font-icons/download-solid.svg" alt="download" loading="lazy" width="13" height="13" alt="download icon">
This and the next one already have an `alt` attribute so the changes are not needed.

2023-04-20 13:27 UTC, XhmikosR commented on translations/zh-cn/README.md
> +  <img src="https://i.imgur.com/NVRZLHv.png" width="640" alt="quicklink" alt="chain">
Same here, it's already present

2023-04-20 13:27 UTC, XhmikosR commented
The rest of the `alt` changes need to properly describe what the image is showing, not just the filename.

2023-04-20 16:57 UTC, Udassi-Pawan commented
Hey @XhmikosR  Thanks for your input and patience, I have made the relevant modifications to the code. Do let me know if any other changes are reqiured.

2023-04-20 18:28 UTC, XhmikosR commented on README.md
> +  <img src="https://raw.githubusercontent.com/GoogleChromeLabs/quicklink/HEAD/assets/images/logos/banner-white-bg.png" width="640">
```suggestion
  <img src="https://raw.githubusercontent.com/GoogleChromeLabs/quicklink/HEAD/assets/images/logos/banner-white-bg.png" alt="" width="640">
```

2023-04-20 18:39 UTC, XhmikosR commented
@Udassi-Pawan thanks for the progress. Could you start the alt text with a capital letter please?

Also, I think we have two more instances:

* https://github.com/GoogleChromeLabs/quicklink/blob/7e52414e83290c91e34465e6fd19418be676a313/site/src/approach.njk#L17
* https://github.com/GoogleChromeLabs/quicklink/blob/7e52414e83290c91e34465e6fd19418be676a313/site/src/approach.njk#L26

2023-04-21 07:31 UTC, Udassi-Pawan commented
Are any other changes required?

2023-04-26 02:11 UTC, addyosmani approved these changes
LGTM

2023-04-26 02:12 UTC, merged